services:
  bundle: &bundle
    env_file: .env
    stdin_open: true
    tty: true
    build: .
    entrypoint: bundle
    command: check
    volumes:
      - .:/usr/src/gem:delegated
      - bundle:/usr/local/bundle:delegated

  rspec:
    <<: *bundle
    entrypoint: bundle exec rspec
    command: --version

volumes:
  bundle: {}
