services:
  bundle: &bundle
    env_file: .env
    stdin_open: true
    tty: true
    build: .
    entrypoint: bundle
    command: check
    volumes:
      - .:/usr/src/gem:delegated
      - bundle:/usr/local/bundle:delegated
      - ~/.gitconfig:/etc/gitconfig:ro
      - ~/.ssh:/root/.ssh:ro
      - ~/.gemrc:/etc/.gemrc:ro
      - ~/.local/share/gem/credentials:/etc/.local/share/gem/credentials:ro

  rspec:
    <<: *bundle
    entrypoint: bundle exec rspec
    command: --version

volumes:
  bundle: {}
